name: portal_host_desktop
description: "Portal Host — Minecraft server manager for desktop"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  drift: ^2.19.0
  sqlite3_flutter_libs: ^0.5.23
  path_provider: ^2.1.3
  go_router: ^14.2.0
  window_manager: ^0.3.8
  tray_manager: ^0.1.1
  http: ^1.2.1
  file_picker: ^8.0.3
  path: ^1.9.0
  intl: ^0.19.0
  archive: ^3.6.1
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.19.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf
