package com.portalhost.world

/**
 * Representative surface color per vanilla biome (1.16–1.21 registry names).
 *
 * Keys are stored without the "minecraft:" prefix for compact lookup.
 * Falls back to [NEUTRAL] for unknown/modded biomes.
 */
object BiomePalette {

    val NEUTRAL: Int = 0xFF7A7A7A.toInt()

    private val BIOME_COLORS: Map<String, Int> = mapOf(
        "ocean" to 0xFF3F76E4.toInt(),
        "deep_ocean" to 0xFF3F76E4.toInt(),
        "warm_ocean" to 0xFF5BC6E8.toInt(),
        "lukewarm_ocean" to 0xFF3F76E4.toInt(),
        "deep_lukewarm_ocean" to 0xFF3F76E4.toInt(),
        "cold_ocean" to 0xFF3F76E4.toInt(),
        "deep_cold_ocean" to 0xFF3F76E4.toInt(),
        "frozen_ocean" to 0xFF8DA6B0.toInt(),
        "deep_frozen_ocean" to 0xFF8DA6B0.toInt(),
        "river" to 0xFF3F76E4.toInt(),
        "frozen_river" to 0xFF8DA6B0.toInt(),

        "plains" to 0xFF91BD59.toInt(),
        "sunflower_plains" to 0xFFB5DB88.toInt(),
        "snowy_plains" to 0xFFF2F4F8.toInt(),
        "snowy_mountains" to 0xFFF2F4F8.toInt(),
        "ice_spikes" to 0xFFB4DCDC.toInt(),
        "desert" to 0xFFDBD2A0.toInt(),
        "desert_hills" to 0xFFDBD2A0.toInt(),
        "desert_lakes" to 0xFFDBD2A0.toInt(),
        "beach" to 0xFFDBD2A0.toInt(),
        "snowy_beach" to 0xFFFAF0C0.toInt(),
        "stone_shore" to 0xFFA2A284.toInt(),
        "stony_shore" to 0xFFA2A284.toInt(),

        "forest" to 0xFF79C05A.toInt(),
        "flower_forest" to 0xFF79C05A.toInt(),
        "birch_forest" to 0xFFB7D975.toInt(),
        "birch_forest_hills" to 0xFFB7D975.toInt(),
        "old_growth_birch_forest" to 0xFFB7D975.toInt(),
        "dark_forest" to 0xFF507A32.toInt(),
        "dark_forest_hills" to 0xFF507A32.toInt(),
        "wooded_hills" to 0xFF79C05A.toInt(),
        "windswept_hills" to 0xFF8AB360.toInt(),
        "windswept_gravelly_hills" to 0xFF8AB360.toInt(),
        "windswept_forest" to 0xFF79C05A.toInt(),
        "windswept_savanna" to 0xFFBDB25F.toInt(),
        "snowy_taiga" to 0xFF596651.toInt(),
        "snowy_taiga_hills" to 0xFF596651.toInt(),
        "snowy_taiga_mountains" to 0xFF596651.toInt(),
        "taiga" to 0xFF596651.toInt(),
        "taiga_hills" to 0xFF596651.toInt(),
        "taiga_mountains" to 0xFF596651.toInt(),
        "old_growth_pine_taiga" to 0xFF596651.toInt(),
        "old_growth_spruce_taiga" to 0xFF596651.toInt(),
        "giant_tree_taiga" to 0xFF596651.toInt(),
        "giant_tree_taiga_hills" to 0xFF596651.toInt(),
        "grove" to 0xFF8DB360.toInt(),
        "snowy_slopes" to 0xFFF2F4F8.toInt(),
        "jagged_peaks" to 0xFFD8D8D8.toInt(),
        "frozen_peaks" to 0xFFE8EEF4.toInt(),
        "stony_peaks" to 0xFFB0B0A0.toInt(),
        "meadow" to 0xFF93C274.toInt(),
        "wooded_mountains" to 0xFF79C05A.toInt(),
        "mountain_edge" to 0xFF8AB360.toInt(),

        "jungle" to 0xFF59C93C.toInt(),
        "jungle_hills" to 0xFF59C93C.toInt(),
        "jungle_edge" to 0xFF59C93C.toInt(),
        "sparse_jungle" to 0xFF59C93C.toInt(),
        "bamboo_jungle" to 0xFF59C93C.toInt(),
        "bamboo_jungle_hills" to 0xFF59C93C.toInt(),

        "swamp" to 0xFF6A7039.toInt(),
        "swamp_hills" to 0xFF6A7039.toInt(),
        "mangrove_swamp" to 0xFF2DB109.toInt(),

        "savanna" to 0xFFBDB25F.toInt(),
        "savanna_plateau" to 0xFFA79D64.toInt(),
        "shattered_savanna" to 0xFFBDB25F.toInt(),
        "shattered_savanna_plateau" to 0xFFA79D64.toInt(),

        "badlands" to 0xFFD69E7A.toInt(),
        "badlands_plateau" to 0xFFBF9040.toInt(),
        "eroded_badlands" to 0xFFD69E7A.toInt(),
        "wooded_badlands" to 0xFFBF9040.toInt(),
        "wooded_badlands_plateau" to 0xFFBF9040.toInt(),

        "mushroom_fields" to 0xFF8AB0D0.toInt(),
        "mushroom_field_shore" to 0xFF8AB0D0.toInt(),
        "cherry_grove" to 0xFFB1A6A4.toInt(),

        "dripstone_caves" to 0xFF9CB168.toInt(),
        "lush_caves" to 0xFF62C140.toInt(),
        "deep_dark" to 0xFF1A1A1A.toInt(),
        "the_void" to 0xFF0E0E0E.toInt(),

        "nether_wastes" to 0xFFBF3B1C.toInt(),
        "crimson_forest" to 0xFF971607.toInt(),
        "warped_forest" to 0xFF1E8421.toInt(),
        "soul_sand_valley" to 0xFF5C5C34.toInt(),
        "basalt_deltas" to 0xFF685565.toInt(),
        "warped_deltas" to 0xFF1E8421.toInt(),
        "soul_sand_valley" to 0xFF5C5C34.toInt(),

        "the_end" to 0xFF1A1A2E.toInt(),
        "small_end_islands" to 0xFF1A1A2E.toInt(),
        "end_midlands" to 0xFF1A1A2E.toInt(),
        "end_highlands" to 0xFF1A1A2E.toInt(),
        "end_barrens" to 0xFF1A1A2E.toInt(),
        "crimson_forest" to 0xFF6A1520.toInt(),
        "warped_forest" to 0xFF1E6E2A.toInt(),
        "nether_wastes" to 0xFF9E3A20.toInt(),
        "soul_sand_valley" to 0xFF4E4830.toInt(),
        "basalt_deltas" to 0xFF4A4040.toInt(),
        "small_end_islands" to 0xFF2A2A4A.toInt(),
        "midlands" to 0xFF2A2A4A.toInt(),
        "highlands" to 0xFF3E3E5E.toInt(),
        "barrens" to 0xFF2A2A4A.toInt(),

        "deepslate_ocean" to 0xFF2C3E50.toInt(),
        "deepslate_river" to 0xFF2D4A5E.toInt(),
        "deepslate_plains" to 0xFF5A5A5A.toInt(),
        "deepslate_forest" to 0xFF3A5A3A.toInt(),
        "deepslate_desert" to 0xFF9A8A60.toInt(),
        "deepslate_beach" to 0xFF8A7A60.toInt(),
        "deepslate_swamp" to 0xFF4A6020.toInt(),
        "deepslate_jungle" to 0xFF3A7A2A.toInt(),
        "deepslate_savanna" to 0xFF8A7A40.toInt(),
        "deepslate_taiga" to 0xFF4A5A40.toInt(),
        "deepslate_dark_forest" to 0xFF2A4020.toInt(),
        "deepslate_badlands" to 0xFF8A5A3A.toInt(),
        "deepslate_mountains" to 0xFF6A6A5A.toInt(),
        "deepslate_dripstone_caves" to 0xFF6A5A40.toInt(),
        "deepslate_lush_caves" to 0xFF4A8A30.toInt(),
        "deepslate_frozen_peaks" to 0xFFB8C0C8.toInt(),
        "deepslate_jagged_peaks" to 0xFFA0A098.toInt(),
        "deepslate_stony_peaks" to 0xFF8A8A7A.toInt(),
        "deepslate_grove" to 0xFF6A7A50.toInt(),
        "deepslate_snowy_slopes" to 0xFFC8D0D8.toInt(),
        "deepslate_meadow" to 0xFF7A9A60.toInt(),
        "deepslate_cherry_grove" to 0xFF9A9088.toInt(),
        "deepslate_bamboo_jungle" to 0xFF4A8A20.toInt(),
        "deepslate_mushroom_fields" to 0xFF7A9AB8.toInt(),
        "deepslate_ice_spikes" to 0xFFA0C0C0.toInt(),
        "deepslate_snowy_plains" to 0xFFC8C8D0.toInt(),
        "deepslate_snowy_beach" to 0xFFC8B898.toInt(),
        "deepslate_snowy_taiga" to 0xFF5A6650.toInt(),
        "deepslate_stony_shore" to 0xFF7A7A6A.toInt(),
        "deepslate_old_growth_birch_forest" to 0xFF7A9A60.toInt(),
        "deepslate_old_growth_pine_taiga" to 0xFF5A6A4A.toInt(),
        "deepslate_old_growth_spruce_taiga" to 0xFF5A6A4A.toInt(),
        "deepslate_giant_tree_taiga" to 0xFF5A6A4A.toInt(),
        "deepslate_grove" to 0xFF6A7A50.toInt(),
        "deepslate_meadow" to 0xFF7A9A60.toInt(),
        "deepslate_wooded_badlands" to 0xFF9A7A50.toInt(),
        "deepslate_eroded_badlands" to 0xFFA08A6A.toInt(),
        "deepslate_wooded_mountains" to 0xFF7A9A68.toInt(),
        "deepslate_mountain_edge" to 0xFF7A8A68.toInt(),
        "deepslate_windswept_hills" to 0xFF7A8A68.toInt(),
        "deepslate_windswept_forest" to 0xFF7A9A68.toInt(),
        "deepslate_windswept_savanna" to 0xFFA89A60.toInt(),
        "deepslate_windswept_gravelly_hills" to 0xFF8A8A78.toInt(),
        "deepslate_stony_peaks" to 0xFF9A9A8A.toInt(),
    )

    fun colorFor(biomeName: String): Int {
        val key = biomeName.removePrefix("minecraft:")
        return BIOME_COLORS[key] ?: NEUTRAL
    }

    fun argbFor(biomeName: String): Long = colorFor(biomeName).toLong() and 0xFFFFFFFFL
}