package com.portalhost.world

/**
 * Maps Minecraft block registry names to a representative top-down ARGB color
 * (0xAARRGGBB in the low 32 bits). Air blocks (and things that are transparent
 * from above) map to null. Unknown blocks fall back to a neutral grey.
 */
object BlockColorTable {

    private const val GREY = 0xFF7A7A7A

    private val AIR_BLOCKS = setOf(
        "minecraft:air",
        "minecraft:cave_air",
        "minecraft:void_air",
        "minecraft:structure_void",
        "minecraft:barrier",
        "minecraft:light",
    )

    private val BLOCK_COLORS: Map<String, Long> = mapOf(
        "minecraft:water" to 0xFF3F76E4L,
        "minecraft:lava" to 0xFFE04919L,
        "minecraft:grass_block" to 0xFF6DBE45L,
        "minecraft:grass_path" to 0xFFC9A96BL,
        "minecraft:dirt_path" to 0xFFC9A96BL,
        "minecraft:dirt" to 0xFF9B7A47L,
        "minecraft:coarse_dirt" to 0xFF8D6B3EL,
        "minecraft:rooted_dirt" to 0xFF7A5B33L,
        "minecraft:farmland" to 0xFF6B4A2EL,
        "minecraft:sand" to 0xFFDBD2A0L,
        "minecraft:red_sand" to 0xFFD4845AL,
        "minecraft:sandstone" to 0xFFE0D6A8L,
        "minecraft:red_sandstone" to 0xFFC97B4AL,
        "minecraft:gravel" to 0xFF969696L,
        "minecraft:stone" to 0xFF8A8A8AL,
        "minecraft:cobblestone" to 0xFF7B7B7BL,
        "minecraft:mossy_cobblestone" to 0xFF6B7B4AL,
        "minecraft:deepslate" to 0xFF5A5A5AL,
        "minecraft:andesite" to 0xFF9B9B9BL,
        "minecraft:granite" to 0xFFA67A6EL,
        "minecraft:diorite" to 0xFFC4C4C4L,
        "minecraft:tuff" to 0xFF6E6E5EL,
        "minecraft:calcite" to 0xFFE8E6D8L,
        "minecraft:bedrock" to 0xFF3E3E3EL,
        "minecraft:snow_block" to 0xFFF4F4F4L,
        "minecraft:snow" to 0xFFFAFAFAL,
        "minecraft:powder_snow" to 0xFFEDEDEDL,
        "minecraft:ice" to 0xFFBBDDF0L,
        "minecraft:packed_ice" to 0xFF9DC9E8L,
        "minecraft:blue_ice" to 0xFF6FA9D8L,
        "minecraft:clay" to 0xFFA8B4C0L,
        "minecraft:mud" to 0xFF3E3328L,
        "minecraft:podzol" to 0xFF5A4633L,
        "minecraft:mycelium" to 0xFF7A6B80L,
        "minecraft:moss_block" to 0xFF5A8A3AL,
        "minecraft:oak_leaves" to 0xFF4E9A3DL,
        "minecraft:birch_leaves" to 0xFF7FBF52L,
        "minecraft:spruce_leaves" to 0xFF3E7A44L,
        "minecraft:dark_oak_leaves" to 0xFF3A6B3FL,
        "minecraft:jungle_leaves" to 0xFF5BBF4FL,
        "minecraft:acacia_leaves" to 0xFF7CAF4AL,
        "minecraft:mangrove_leaves" to 0xFF3E7A44L,
        "minecraft:cherry_leaves" to 0xFFE8B0B8L,
        "minecraft:azalea_leaves" to 0xFF6D9F4AL,
        "minecraft:flowering_azalea_leaves" to 0xFF6D9F4AL,
        "minecraft:oak_log" to 0xFF9B7A47L,
        "minecraft:birch_log" to 0xFFD8D4C4L,
        "minecraft:spruce_log" to 0xFF5A4A35L,
        "minecraft:dark_oak_log" to 0xFF4A3520L,
        "minecraft:jungle_log" to 0xFF6B5A3AL,
        "minecraft:acacia_log" to 0xFF8A837AL,
        "minecraft:mangrove_log" to 0xFF5A4633L,
        "minecraft:cherry_log" to 0xFF4A3535L,
        "minecraft:oak_planks" to 0xFFB08A52L,
        "minecraft:spruce_planks" to 0xFF7A6038L,
        "minecraft:birch_planks" to 0xFFE0D8B0L,
        "minecraft:jungle_planks" to 0xFF9E7A4AL,
        "minecraft:acacia_planks" to 0xFFC47852L,
        "minecraft:dark_oak_planks" to 0xFF5A4028L,
        "minecraft:mangrove_planks" to 0xFF8A5A3AL,
        "minecraft:cherry_planks" to 0xFFC8A0A0L,
        "minecraft:crimson_planks" to 0xFF7A3030L,
        "minecraft:warped_planks" to 0xFF2E7A6EL,
        "minecraft:crimson_nylium" to 0xFF9E2A2AL,
        "minecraft:warped_nylium" to 0xFF2E7A4EL,
        "minecraft:red_mushroom_block" to 0xFFB03830L,
        "minecraft:brown_mushroom_block" to 0xFF7A5A3AL,
        "minecraft:mushroom_stem" to 0xFFE0D8C0L,
        "minecraft:terracotta" to 0xFF9E6B53L,
        "minecraft:white_terracotta" to 0xFFD0B69AL,
        "minecraft:orange_terracotta" to 0xFFA96A44L,
        "minecraft:red_terracotta" to 0xFF8A4A36L,
        "minecraft:yellow_terracotta" to 0xFFB08A44L,
        "minecraft:green_terracotta" to 0xFF5A6B3AL,
        "minecraft:blue_terracotta" to 0xFF3A4A72L,
        "minecraft:gray_terracotta" to 0xFF5E5E5EL,
        "minecraft:white_concrete" to 0xFFE8E8E8L,
        "minecraft:gray_concrete" to 0xFF7A7A7AL,
        "minecraft:black_concrete" to 0xFF2A2A2AL,
        "minecraft:white_wool" to 0xFFE8E8E8L,
        "minecraft:red_wool" to 0xFFB0382EL,
        "minecraft:blue_wool" to 0xFF3A4AB0L,
        "minecraft:stone_bricks" to 0xFF8A8A8AL,
        "minecraft:mossy_stone_bricks" to 0xFF6B7B4AL,
        "minecraft:bricks" to 0xFF9E5A4AL,
        "minecraft:smooth_stone" to 0xFF9A9A9AL,
        "minecraft:quartz_block" to 0xFFE8E4D8L,
        "minecraft:copper_block" to 0xFFC96A4AL,
        "minecraft:exposed_copper" to 0xFFB07A5AL,
        "minecraft:weathered_copper" to 0xFF6B8A5AL,
        "minecraft:oxidized_copper" to 0xFF4A8A7AL,
        "minecraft:iron_block" to 0xFFD8D8D8L,
        "minecraft:gold_block" to 0xFFF4C44AL,
        "minecraft:diamond_block" to 0xFF5AD8D8L,
        "minecraft:emerald_block" to 0xFF5AE85AL,
        "minecraft:lapis_block" to 0xFF2A3AB0L,
        "minecraft:pumpkin" to 0xFFD8872AL,
        "minecraft:carved_pumpkin" to 0xFFD8872AL,
        "minecraft:jack_o_lantern" to 0xFFD8872AL,
        "minecraft:melon" to 0xFF6B9E3EL,
        "minecraft:hay_block" to 0xFFC9B25AL,
        "minecraft:dried_kelp_block" to 0xFF3A4A2EL,
        "minecraft:bamboo_block" to 0xFF5A9E3EL,
        "minecraft:bamboo" to 0xFF5A9E3EL,
        "minecraft:amethyst_block" to 0xFF8A5AA8L,
        "minecraft:obsidian" to 0xFF2A2430L,
        "minecraft:crying_obsidian" to 0xFF38204AL,
        "minecraft:netherrack" to 0xFF8B3D37L,
        "minecraft:nether_bricks" to 0xFF3A2A30L,
        "minecraft:red_nether_bricks" to 0xFF4A2A2AL,
        "minecraft:soul_sand" to 0xFF5C5C34L,
        "minecraft:soul_soil" to 0xFF4A4A2AL,
        "minecraft:basalt" to 0xFF4A4A4AL,
        "minecraft:smooth_basalt" to 0xFF4A4A4AL,
        "minecraft:blackstone" to 0xFF2E2E2EL,
        "minecraft:gilded_blackstone" to 0xFF3E3E3AL,
        "minecraft:magma_block" to 0xFF8B3D2AL,
        "minecraft:end_stone" to 0xFFCFDBC4L,
        "minecraft:end_stone_bricks" to 0xFFCFDBC4L,
        "minecraft:chorus_plant" to 0xFF9E5AC0L,
        "minecraft:chorus_flower" to 0xFFB06AD8L,
        "minecraft:sculk" to 0xFF0E2A2AL,
        "minecraft:seagrass" to 0xFF3E8A3EL,
        "minecraft:tall_seagrass" to 0xFF3E8A3EL,
        "minecraft:kelp" to 0xFF3E7A3EL,
        "minecraft:sea_lantern" to 0xFFB8E8E8L,
        "minecraft:prismarine" to 0xFF6BA8A8L,
        "minecraft:prismarine_bricks" to 0xFF5A8A8AL,
        "minecraft:dark_prismarine" to 0xFF3E5A5AL,
        "minecraft:turtle_egg" to 0xFFE8E4D8L,
        "minecraft:glowstone" to 0xFFD8C46BL,
        "minecraft:shroomlight" to 0xFFE8A84AL,
    )

    /**
     * Returns the ARGB color for the top block of a column, or null if the block
     * is transparent from above (air) or unknown.
     */
    fun colorFor(blockName: String): Long? {
        val key = blockName.removePrefix("minecraft:")
        if (AIR_BLOCKS.contains("minecraft:$key")) return null
        return BLOCK_COLORS["minecraft:$key"] ?: GREY
    }
}
